import { useCallback, useEffect, useState, type FormEvent } from "react";
import { grade, type Verdict } from "../grade";
import {
  getExercises,
  isWarmed,
  peek,
  prefetch,
  replaceAt,
  setAt,
  sourceOf,
} from "../exerciseCache";
import {
  allAttempts,
  computeStats,
  recordAttempt,
  weakPrompts,
  type Stats,
} from "../store";
import type { Exercise, ExerciseType } from "../types";

const TYPES: { id: ExerciseType; label: string }[] = [
  { id: "en2pl", label: "English → Polish" },
  { id: "pl2en", label: "Polish → English" },
  { id: "cloze", label: "Fill the gap" },
];

const BATCH = 5;

export default function Exercises() {
  const [type, setType] = useState<ExerciseType>("en2pl");
  const [index, setIndex] = useState(0);
  const [value, setValue] = useState("");
  const [verdict, setVerdict] = useState<Verdict | null>(null);
  const [revealed, setRevealed] = useState(false);
  const [loading, setLoading] = useState(() => !isWarmed("en2pl"));
  const [source, setSource] = useState<"generated" | "seed" | null>(() =>
    sourceOf("en2pl"),
  );
  const [stats, setStats] = useState<Stats | null>(null);
  const [score, setScore] = useState({ right: 0, wrong: 0 });
  const [warming, setWarming] = useState(false);

  const current: Exercise | undefined = setAt(type, index);

  // Draw straight from the cache first so switching tabs is instant.
  useEffect(() => {
    const cached = peek(type);
    if (cached) {
      setLoading(false);
      setSource(sourceOf(type));
    } else {
      setLoading(true);
    }
    setIndex(0);
    setValue("");
    setVerdict(null);
    setRevealed(false);
  }, [type]);

  // Warm every type once, sequentially, so later switches are instant.
  useEffect(() => {
    const missing = TYPES.filter((t) => !isWarmed(t.id)).map((t) => t.id);
    if (missing.length === 0) return;

    let cancelled = false;
    setWarming(true);
    void prefetch(missing, BATCH, weakPrompts()).then(() => {
      if (cancelled) return;
      setWarming(false);
      setSource(sourceOf(type));
    });
    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const load = useCallback(
    async (t: ExerciseType) => {
      setLoading(true);
      try {
        await getExercises(t, BATCH, weakPrompts());
        setSource(sourceOf(t));
      } catch {
        /* keep whatever is cached */
      } finally {
        setLoading(false);
      }
    },
    [],
  );

  useEffect(() => {
    if (!isWarmed(type) && !peek(type)) void load(type);
  }, [type, load]);

  function submit(e: FormEvent) {
    e.preventDefault();
    if (!current || revealed || !value.trim()) return;

    const result = grade(current.answer, value);
    const ok = result !== "wrong";
    setVerdict(result);
    setRevealed(true);

    recordAttempt({
      type: current.type,
      prompt: current.prompt,
      answer: current.answer,
      correct: ok,
    });
    setScore((s) => ({ right: s.right + (ok ? 1 : 0), wrong: s.wrong + (ok ? 0 : 1) }));
    setStats(computeStats(allAttempts()));
  }

  /**
   * Wrong answers are replaced by a fresh generated exercise for the same slot,
   * so the learner meets new material instead of memorising the miss. The
   * replacement is fetched per-slot and swapped in when it arrives.
   */
  function advance() {
    const wasWrong = verdict === "wrong";

    setVerdict(null);
    setRevealed(false);
    setValue("");

    const advanceIndex = () => {
      if (index + 1 < (peek(type)?.length ?? 0)) setIndex(index + 1);
      else void load(type);
    };

    if (wasWrong && current) {
      const slot = index;
      const replacement = getExercises(type, 1, [...weakPrompts(), current.prompt], true);
      void replacement
        .then(([fresh]) => {
          if (fresh) replaceAt(type, slot, { ...fresh, type });
        })
        .catch(() => undefined);
    }

    advanceIndex();
  }

  const total = peek(type)?.length ?? 0;

  return (
    <>
      <div className="panel-head">
        <h2>Exercises</h2>
        <div className="head-right">
          {warming && <span className="warming">preparing other types…</span>}
          {source && (
            <span className={`badge-src ${source}`}>
              {source === "generated" ? "generated by gemma3" : "built-in set"}
            </span>
          )}
        </div>
      </div>

      <div className="type-tabs">
        {TYPES.map((t) => (
          <button
            key={t.id}
            className={type === t.id ? "active" : ""}
            onClick={() => setType(t.id)}
          >
            {t.label}
            {isWarmed(t.id) && <span className="tick">•</span>}
          </button>
        ))}
      </div>

      <div className="exercise-body">
        {loading && !current && (
          <p className="muted">
            Generating exercises with gemma3 — first call after idle loads the model,
            expect up to ~30s.
          </p>
        )}

        {!loading && !current && (
          <p className="muted">No exercises available. Is Ollama running?</p>
        )}

        {current && (
          <>
            <div className="progress-line">
              <span>
                {index + 1} / {total}
              </span>
              <span className="score">
                ✓ {score.right} · ✗ {score.wrong}
              </span>
            </div>

            <div className="prompt-card">
              <p className="prompt-text">{current.prompt}</p>
              {current.type === "cloze" && (
                <p className="hint">Type the missing word only.</p>
              )}
            </div>

            <form onSubmit={submit} className="exercise-form">
              <input
                value={value}
                onChange={(e) => setValue(e.target.value)}
                disabled={revealed}
                placeholder={
                  current.type === "pl2en" ? "Write it in English…" : "Twoja odpowiedź…"
                }
                autoFocus
              />
              {revealed ? (
                <button type="button" onClick={advance}>
                  Next
                </button>
              ) : (
                <button type="submit" disabled={!value.trim()}>
                  Check
                </button>
              )}
            </form>

            {revealed && (
              <div className={`feedback ${verdict ?? "wrong"}`}>
                <p>
                  {verdict === "correct" && "Dobrze! "}
                  {verdict === "close" && "Prawie — "}
                  {verdict === "wrong" && "Poprawna odpowiedź: "}
                  <strong>{current.answer}</strong>
                </p>
                {current.explanation && (
                  <p className="explain">{current.explanation}</p>
                )}
              </div>
            )}
          </>
        )}
      </div>

      {stats && stats.total > 0 && (
        <p className="muted foot">
          Overall {Math.round((stats.accuracy ?? 0) * 100)}% over {stats.total} answers.
        </p>
      )}
    </>
  );
}