import { useCallback, useEffect, useState, type FormEvent } from "react";
import { fetchExercises } from "../api";
import { grade, type Verdict } from "../grade";
import {
  allAttempts,
  computeStats,
  recordAttempt,
  weakPrompts,
  type Stats,
} from "../store";
import type { Attempt, Exercise, ExerciseType } from "../types";

const TYPES: { id: ExerciseType; label: string; blurb: string }[] = [
  { id: "en2pl", label: "English → Polish", blurb: "Read Polish, say it in English" },
  { id: "pl2en", label: "Polish → English", blurb: "Read English, say it in Polish" },
  { id: "cloze", label: "Fill the gap", blurb: "One missing word in a Polish sentence" },
  { id: "order", label: "Put it in order", blurb: "Rebuild the Polish sentence" },
];

export default function Exercises() {
  const [type, setType] = useState<ExerciseType>("en2pl");
  const [queue, setQueue] = useState<Exercise[]>([]);
  const [index, setIndex] = useState(0);
  const [value, setValue] = useState("");
  const [verdict, setVerdict] = useState<Verdict | null>(null);
  const [revealed, setRevealed] = useState(false);
  const [loading, setLoading] = useState(false);
  const [source, setSource] = useState<"generated" | "seed" | null>(null);
  const [stats, setStats] = useState<Stats | null>(null);
  const [score, setScore] = useState({ right: 0, wrong: 0 });

  const current = queue[index] ?? null;

  const load = useCallback(async (t: ExerciseType) => {
    setLoading(true);
    setVerdict(null);
    setRevealed(false);
    setValue("");
    try {
      const set = await fetchExercises(t, 5, weakPrompts());
      setQueue(set.exercises);
      setSource(set.source);
      setIndex(0);
    } catch {
      setQueue([]);
      setSource("seed");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    void load(type);
  }, [type, load]);

  function submit(e: FormEvent) {
    e.preventDefault();
    if (!current || revealed || !value.trim()) return;

    const result = grade(current.answer, value);
    const ok = result !== "wrong";
    setVerdict(result);
    setRevealed(true);

    const attempt: Omit<Attempt, "at"> = {
      type: current.type,
      prompt: current.prompt,
      answer: current.answer,
      correct: ok,
    };
    recordAttempt(attempt);
    setScore((s) => ({ right: s.right + (ok ? 1 : 0), wrong: s.wrong + (ok ? 0 : 1) }));
    setStats(computeStats(allAttempts()));
  }

  function advance() {
    setVerdict(null);
    setRevealed(false);
    setValue("");
    if (index + 1 < queue.length) setIndex(index + 1);
    else void load(type);
  }

  const done = !loading && queue.length === 0;

  return (
    <>
      <div className="panel-head">
        <h2>Exercises</h2>
        {source && (
          <span className={`badge-src ${source}`}>
            {source === "generated" ? "generated by gemma3" : "built-in set"}
          </span>
        )}
      </div>

      <div className="type-tabs">
        {TYPES.map((t) => (
          <button
            key={t.id}
            className={type === t.id ? "active" : ""}
            onClick={() => setType(t.id)}
          >
            {t.label}
          </button>
        ))}
      </div>

      <div className="exercise-body">
        {loading && (
          <p className="muted">
            Generating exercises… (first call after idle loads the model, expect ~10s)
          </p>
        )}

        {done && <p className="muted">No exercises available. Is Ollama running?</p>}

        {current && !loading && (
          <>
            <div className="progress-line">
              <span>
                {index + 1} / {queue.length}
              </span>
              <span className="score">
                ✓ {score.right} · ✗ {score.wrong}
              </span>
            </div>

            <div className="prompt-card">
              <p className="prompt-text">{current.prompt}</p>
              {current.type === "cloze" && (
                <p className="hint">Type the missing word only.</p>
              )}
              {current.type === "order" && (
                <p className="hint">Type the sentence in the correct order.</p>
              )}
            </div>

            <form onSubmit={submit} className="exercise-form">
              <input
                value={value}
                onChange={(e) => setValue(e.target.value)}
                disabled={revealed}
                placeholder={
                  current.type === "pl2en" ? "Write it in English…" : "Twoja odpowiedź…"
                }
                autoFocus
              />
              {revealed ? (
                <button type="button" onClick={advance}>
                  Next
                </button>
              ) : (
                <button type="submit" disabled={!value.trim()}>
                  Check
                </button>
              )}
            </form>

            {revealed && (
              <div className={`feedback ${verdict ?? "wrong"}`}>
                <p>
                  {verdict === "correct" && "Dobrze! "}
                  {verdict === "close" && "Prawie — "}
                  {verdict === "wrong" && "Poprawna odpowiedź: "}
                  <strong>{current.answer}</strong>
                </p>
                {current.explanation && <p className="explain">{current.explanation}</p>}
              </div>
            )}
          </>
        )}
      </div>

      {stats && stats.total > 0 && (
        <p className="muted foot">
          Overall {Math.round((stats.accuracy ?? 0) * 100)}% over {stats.total} answers.
        </p>
      )}
    </>
  );
}